import '@/assets/css/index.css';
import '@/assets/themes.css';
import { initTheme } from '@/composables/useToggleTheme';
import axiosPlugin from '@/plugins/axios';
import { createPinia } from 'pinia';
import { createApp } from 'vue';
import App from './App.vue';
import './assets/css/index.css';
import router from './router/index';
const pinia = createPinia();
initTheme();
const app = createApp(App);
app.use(router);
app.use(pinia);
app.use(axiosPlugin);
app.mount('#app');
